### ISSUE TITLE
Release PRs are not being created

### ISSUE THREAD

**Issue by frankyn** [googleapis/java-storage-nio#147]
PR's auto-generated automatically when releases are ready aren't being generated and not sure why this is the case.

@kolea2 or @chingor13 do you have ideas? I'm a bit confused.

**Comment by kolea2** [comment]
I tried adding the force run label, but looks like it's still stuck: https://github.com/googleapis/java-storage-nio/pull/143#event-3455403428. @chingor13 any ideas?

**Comment by frankyn** [comment]
Update syncing with @chingor13 offline. Releases are auto-created when PRs are labeled (`fix:`), otherwise they're not auto created for: `ci, chore, test`. The latest PR should have been marked `fix:` instead of `test:`, @chingor13 is helping give a workaround.
