### ISSUE TITLE
Implement writeWithResponse in FakeStorageRpc

### ISSUE THREAD

**Issue by rbraeunlich** [googleapis/java-storage-nio#175]
**Is your feature request related to a problem? Please describe.**
With Pull Request #135 the `FakeStorageRpc` class extends `StorageRpcTestBase` and now google-cloud-storage is a needed dependency when using the class in tests. In google-cloud-storage the implementation of BlobWriteChannel has been changed a month ago (https://github.com/googleapis/java-storage/pull/269/files#diff-8561e6a9172119adf8e882a3f5298d6bR69) so that `flushBuffer` now calls `writeWithResponse` instead of `write`.
`writeWithResponse` is neither implemented in `FakeStorageRpc` nor in `StorageRpcTestBase`, which causes my tests to crash now, which didn't happen before. 
 
**Describe the solution you'd like**
Please implement the method. Since the response is a StorageObject it shouldn't cause any problems.

**Describe alternatives you've considered**
My workaround is now to set my dependency to google-cloud-storage fixed to 1.110.0. But this pins me on this version.

**Comment by MartinHaeusler** [comment]
The same thing happened to me as well. Can't upgrade my cloud storage client until this issue is resolved...
