### ISSUE TITLE
Is this library still considered alpha?

### ISSUE THREAD

**Issue by lbergelson** [googleapis/java-storage-nio#188]
I noticed that the latest releases are no longer listed as alpha?  Does that mean this now is considered general release?

**Comment by frankyn** [comment]
Hi @lbergelson,

We are still in Alpha stage and we are starting to discuss release stage of this library. We don't have anything meaningful to report right now.
https://github.com/googleapis/java-storage-nio#versioning

> It is currently in major version zero (0.y.z), which means that anything may change at any time and the public API should not be considered stable.


Thank you for your patience.

**Comment by lbergelson** [comment]
No problem.  Thanks for the info.  I was just surprised that the maven coordinates had dropped it.
