### ISSUE TITLE
FakeStorageRpc: Consider filtering by bucket *and* prefix.

### ISSUE THREAD

**Issue by yuri-sergiichuk** [googleapis/java-storage-nio#207]
#### Environment details

1. FakeStorageRpc
2. OS type and version: Win 10
3. Java version: java 8
4. google-cloud-nio version(s): 0.121.2

#### Steps to reproduce

1. Add object with name "test-object" to bucket "first-bucket",
2. Add object with name "test-object" to bucket "second-bucket".
3. List objects in "first-bucket" with "test-" prefix.
4. Both "test-object" files from "first-bucket" and "second-bucket" are returned.

#### Any additional information below

The `list` method in the `FakeStorageRpc` does not take into account the `bucket` metadata:

```java
    for (StorageObject so : metadata.values()) {
      if (!so.getName().startsWith(prefix)) {                       // <---------- here's the problem
        continue;
      }
      if (processedAsFolder(so, delimiter, prefix, folders)) {
        continue;
      }
      so.setSize(size(so));
      values.add(so);
    }
```

Technically, just adding an extra check to compare the `so.getBucket()` with `bucket` should be enough to resolve the issue.

**Comment by yuri-sergiichuk** [comment]
@athakor Hi, thx for taking a look at it. Do you think it's smth we can expect to be resolved soon?

I can create a PR with a fix if it'll help speed it up.

**Comment by athakor** [comment]
@yuri-sergiichuk thanks for your patience  don't worry i will fixed it soon.

**Comment by yuri-sergiichuk** [comment]
@athakor thx for fixing the bug.

Is there any plan to release a new version with this fix any time soon? I'd really love to have the fixed version ASAP as it kind of blocking our local dev tests.

**Comment by athakor** [comment]
> @athakor thx for fixing the bug.
> 
> Is there any plan to release a new version with this fix any time soon? I'd really love to have the fixed version ASAP as it kind of blocking our local dev tests.

@yuri-sergiichuk i am not sure but it might done soon
