### ISSUE TITLE
Error when we try to check if a file is a directory on google buckets

### ISSUE THREAD

**Issue by malkhalidi-atypon** [googleapis/java-storage-nio#352]
We are moving to google buckets for storage as part of our cloud migration, CloudStorageFileSystem is a neat solution for this, a drop in for us.

The problem that we are facing is when we try to check if a file is a directory using: 

```
Path path = filesystem.get("testfileNotfolder");
if (Files.isDirectory(path)) {
.....
} else {
.....
}
```

It complains with an error about a missing permission:
```json
{
"code" : 403,
"errors" : [ {
"domain" : "global",
"message" : "xxxxxxxxxxxxxxxxxxxxxx does not have serviceusage.services.use access to xxxxxxxxxxxxxxxxxxx",
"reason" : "forbidden"
} ],
"message" : "xxxxxxxxxxxxxxxxxxxxxx does not have serviceusage.services.use access to project xxxxxxxxxxxxxxxxxxx."
}
```

This has been filed before as **https://github.com/googleapis/java-storage-nio/issues/61** but it never went anywhere, the current way of us having this working is granting it an editor/owner role on the project, which is too much access for a storage API credentials.

Please check the previous filed ticket, it estates that if we don't pass the project, it will work fine, which is what we want and that won't require permission: **serviceusage.services.use** and that works fine if we try to execute the code in debugging, the change isn't much.

Can you please provide a solution for this issue as this is still happening, we need either to have a way to configure not passing the project, because clearly the API works without passing it, or a way to grant that permission only to the credential of the API as it doesn't appear to be a way to do so.

This library is really convenient and having this role assigned to the storage credential will simply not work/allowed to use it in production and we will be forced to use another library.

**Comment by hdimitriou** [comment]
@frankyn any progress on this? We are also facing this and are reluctant in granting this permission 'serviceusage.services.use'

**Comment by frankyn** [comment]
Hi folks,

The issue here is that the service account is expected to have `Project Owner` role granted to it.

To get around this issue, you'll need to disable Requester Pays on the Cloud Storage bucket if it's enabled and not send UserProject in requests.

To disable UserProject forcibly:
```java
CloudStorageConfiguration config =
        CloudStorageConfiguration.builder()
            .autoDetectRequesterPays(false)
            .userProject(null)
            .build();
    CloudStorageFileSystem testBucket = CloudStorageFileSystem.forBucket("anima-bucket", config);
    CloudStoragePath test = testBucket.getPath("test");
    if(Files.isDirectory(test)) {
      System.out.println("???");
    }
```

Based on current investigation though, there might be a book in the look up requests that still contains UserProject in the URI.
