### ISSUE TITLE
Linkage Error found while exposing getNotification in storage.

### ISSUE THREAD

**Issue by athakor** [googleapis/java-storage-nio#38]
Build failed of  [storage -138](https://github.com/googleapis/java-storage/issues/138) due to linkage error :
```
SEVERE: Newly introduced problem:
(google-cloud-nio-0.120.0-alpha.jar) com.google.cloud.storage.contrib.nio.testing.FakeStorageRpc's method getNotification(String arg1, String arg2) is not implemented in the class
  referenced from com.google.cloud.storage.spi.v1.StorageRpc (google-cloud-storage-1.104.0.jar)
```
**Solution:**

https://github.com/googleapis/java-storage-nio/blob/df030b86e43dd8ea627b25e2ea7700510abf2ba3/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java#L632-L644

We have to override `getNotification` method  in `FakeStorageRpc.java` once  [storage - 138](https://github.com/googleapis/java-storage/issues/138) gets merged.

```javascript
  @Override
  public Notification getNotification(String bucket, String notification){
    throw new UnsupportedOperationException();
  }
```

**Comment by frankyn** [comment]
Addressed in #135
