### ISSUE TITLE
Which method is used to read uncompressed gzip file from GCS object

### ISSUE THREAD

**Issue by yuanyuan-gl** [googleapis/java-storage-nio#438]
We'd like to be able to leverage the gzip transcoding feature of GCS, as we currently spend a great deal of time decompressing such files for processing in our pipeline. We currently use the cloud storage NIO library to access files, however this method (and the ReadChannel class that facilitates it) does not appear to support transcoding.
Questions:
- Is there a way to use the NIO library to read uncompressed files from GCS directly?
- Is there formal documentation anywhere with respect to transcoding and the java client library?

**Comment by tritone** [comment]
Unfortunately this is not super well documented, but I did some research and found the following:

* We don't currently support transcoding via java-storage-nio. Adding a flag to do this would be a feature request.
* When using the standard java-storage client, transcoding will happen by default (when possible) when using `blob.downloadTo` method, but will not happen when using a `ReadChannel` directly. See googleapis/java-storage#321 for more details on this; I think this is a quirk of the library and we'd like to add more user control there via a flag to `downloadTo` as well.
* Obviously transcoding also requires all of the conditions in the [docs](https://cloud.google.com/storage/docs/transcoding#decompressive_transcoding) to be fulfilled (namely that the object is a valid gzip and stored with `Content-Encoding: gzip`.

**Comment by tritone** [comment]
I'm going to close out this issue and re-open a feature request.
