### ISSUE TITLE
FileSystemNotFoundException: Provider "gs" not installed

### ISSUE THREAD

**Issue by lordcoste** [googleapis/java-storage-nio#547]
Hi, I'm getting this error on app engine standard java11:

```
java.nio.file.FileSystemNotFoundException: Provider "gs" not installed
    at java.base/java.nio.file.Path.of(Path.java:212)
    at java.base/java.nio.file.Paths.get(Paths.java:97)
```

Is there anything else I should do besides adding the dependency in the pom?

```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-nio</artifactId>
  <version>0.122.13</version>
</dependency>
```

Best regards

**Comment by cojenco** [comment]
Hi @lordcoste, thanks for filing the question. The `google-cloud-nio` artifact ships a scheme handler for `gs` URI. We do recommend deferring to libraries-bom for the version as is shown in the [first sample here](https://github.com/googleapis/java-storage-nio#quickstart). If you can try that out, and see if you still run into the exception.

**Comment by averikitsch** [comment]
Hi @lordcoste , it looks like the conventional Spring boot packaging here isn't packaging the dependency in the needed way. Usually you'll see something like:
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <version>2.4.5</version>
    <executions>
        <execution>
            <goals>
                <goal>repackage</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

However, for the "gs" provider to be accessible it needs to be in the 'lib/' folder. You can package it manually by copying the dependencies and then creating the JAR (this is based on the [springboot-helloworld](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java11/springboot-helloworld) sample:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-dependency-plugin</artifactId>
  <executions>
      <execution>
          <id>copy-dependencies</id>
          <phase>prepare-package</phase>
          <goals>
              <goal>copy-dependencies</goal>
          </goals>
          <configuration>
              <outputDirectory>
                  ${project.build.directory}/lib
              </outputDirectory>
          </configuration>
      </execution>
  </executions>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-jar-plugin</artifactId>
<configuration>
    <archive>
        <manifest>
            <addClasspath>true</addClasspath>
            <classpathPrefix>lib/</classpathPrefix>
            <mainClass>
              com.example.appengine.springboot.SpringbootApplication
            </mainClass>
        </manifest>
    </archive>
</configuration>
</plugin>
```
