### ISSUE TITLE
Consider changing CloudStoragePath.toString() result

### ISSUE THREAD

**Issue by lbergelson** [googleapis/java-storage-nio#73]
**Is your feature request related to a problem? Please describe.**
People tend to use `path.toString()` when writing error messages since it's easier than `path.toUri().toString()`.  This problem is that with `CloudStoragePath.toString()` it omits the scheme and the bucket in the result.  So users get back an error message that doesn't even include information about the fact that it's a `gs://` path.  It causes confusion, people end up looking at their local file system for problems, etc.

It is definitely possible to always use toUri().toString(), but it's kind of ugly boilerplate and people forget to do so.

**Describe the solution you'd like**
Could we change the behavior of `CloudStoragePath.toString()` to just be the result of `toUri().toString()`?  I'm happy to introduce the patch myself.  There might be weirdness about relative paths that we'd to do something slightly more sophisticated, but that seems to me that that's more reason change the toString representation rather than relying on users to always convert it themselves.  We could do something slightly more sophisticated if we wanted some representation of "this is a relative google cloud path".

**Describe alternatives you've considered**
It is definitely possible to always use `toUri().toString()`, but it's kind of ugly boilerplate and people forget to do so, especially if they only are testing on local files and not remote ones.  There're regular rounds of whack-a-mole to fix it as it's reintroduced to codebases.

**Comment by frankyn** [comment]
Hi @lbergelson,

Thanks for the feedback! For now we've decided to forgo this FR because there's a solution to get the information needed. If more folks chime in asking for this FR we will reconsider.

Cheers

**Comment by lbergelson** [comment]
Reasonable.  Thanks for taking a look at it.
