### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by clarkperkins** [googleapis/java-storage-nio#75]
Hi, I was just wondering when there will be a new release of this repo.  I've noticed there hasn't been a new google-cloud-nio jar published to maven central since this PR was merged: https://github.com/googleapis/google-cloud-java/pull/6740

**Comment by clarkperkins** [comment]
Any updates on this?  This bug causes a whole bunch of tests to fail in some of our code, because we use the `Blob::downloadTo` method.  It would be very helpful to us if you could release a version with the fix so we don't have to copy FakeStorageRpc into our codebase.

**Comment by frankyn** [comment]
Hi @clarkperkins,

Thanks for filing the issue.  I'm working on cutting a new release. Apologies for the delay.

**Comment by clarkperkins** [comment]
Thank you!

**Comment by clarkperkins** [comment]
Hi, I'm sorry to pester again, but are there any updates on this?

**Comment by frankyn** [comment]
Thanks for the ping @clarkperkins. I'm resolving a dependency conflict in #89 and will cut a release shortly after.

Thank you for your patience.

**Comment by frankyn** [comment]
I have cut a release and pending release to Maven central. Thanks for your patience, closing issue.
