### ISSUE TITLE
Integration tests rely on no default project found

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-storage-nio#8]
See sample failing integration test: https://source.cloud.google.com/results/invocations/9f7be5ed-d63f-4a9a-9d5f-ca43996197bf/targets/github%2Fjava-storage-nio%2Fgoogle-cloud-nio%2Ftarget%2Ffailsafe-reports/tests;group=com.google.cloud.storage.contrib.nio.it.ITGcsNio%28sponge_log%29;test=testCantCreateWithoutUserProject;row=1

Our integration tests run on a GCE instance with a service account that has a default project set.

**Comment by athakor** [comment]
@chingor13  Locally working fine.something weird, i am not sure, why it's getting failed on test environment.

**Comment by frankyn** [comment]
@chingor13 started work in #45 

Copying response in here:

> Hi @chingor13, I was diving into #8 and found your PR.
> 
> IIUC, the issue here is that the service account used to execute tests has Project Owner role granted.
> I was able to pass tests locally when my service account is only granted Project Editor role. The reason is that Project Owner has [`serviceusage.services.use`](https://cloud.google.com/storage/docs/requester-pays). This lets requests succeed without having the user set a user_project as expected.
> 
> An alternative solution to this is to create a new service account for this project that only has Project Editor role. 
> 
> This was encountered here as well: https://github.com/googleapis/google-cloud-java/issues/3448
> 
> Totally open to discussing this more. I don't know where the service account is stored but I can help update it with a new service account credentials file to unblock this failure.
> 
>

**Comment by chingor13** [comment]
We changed the permissions and this seems to be fixed by dropping to Project Editor. Thanks @frankyn
